language: generic

sudo: required

services:
  - docker

branches:
  only:
    - hangjin

script:
#  - docker build -t hangs0908/bookstore-frontend ./front-end/books
  - docker build -t hangs0908/bookstore-backend -f ./back-end/Dockerfile .
#  - docker build -t hangs0908/bookstore-nginx ./nginx

after_success:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hangs0908/bookstore-frontend
  - docker push hangs0908/bookstore-backend
  - docker push hangs0908/bookstore-nginx