language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/app/bookstore/back-end/.gradle'

script:
  - "cd app"
  - "sudo ./backend.sh"
#  - "./gradlew clean build --exclude-task test"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - bookstore0324@gmail.com