server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hidernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          description:
            sql:
              BasicBinder: TRACE


